#
#       PROBLEM
#
# Each new term in the Fibonacci sequence is generated by adding the
# previous two terms. By starting with 1 and 2, the first 10 terms will be:

# 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

# By considering the terms in the Fibonacci sequence whose values do not
# exceed four million, find the sum of the even-valued terms.


# def fib(n)
#   return n if (0..1).include? n
#   fib(n-1) + fib(n-2) if n > 1
# end

#puts fib(1000)




def fib(n)
  return n if n < 2
  vals = [0, 1]
  (n-1).times do 
    vals.push(vals[-1] + vals[-2]) 
  end
  return vals.last
end



puts fib(33)

fibonaci_sum = 0


(1..33).each do |x|

	if x % 2 == 0
	fibonaci_sum =+ fib(x)
	end
end

puts " "
puts fibonaci_sum

